# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 389984a1ca9d291e84aef44100a534d8b3f62d23ed03004e46a66252b8a92fc3802ea33d717eb75d08bf4bc1867543023ba0063b49961aaced38a6ffa05798bf

test:
  secret_key_base: bf2299ecc79b56bf2552d1007795beb31a05473e2dccdc6a494419fb3f30dce693f02961789265b07c1e76ab4b87c0c7288d9cd09047dad4f4c486009c021083

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
